<script type="module">
  // Import the functions you need from the SDKs you need
  import { initializeApp } from "https://www.gstatic.com/firebasejs/12.0.0/firebase-app.js";
  import { getAnalytics } from "https://www.gstatic.com/firebasejs/12.0.0/firebase-analytics.js";
  // TODO: Add SDKs for Firebase products that you want to use
  // https://firebase.google.com/docs/web/setup#available-libraries

  // Your web app's Firebase configuration
  // For Firebase JS SDK v7.20.0 and later, measurementId is optional
  const firebaseConfig = {
    apiKey: "AIzaSyAu7MWQjdQmKSU-0_WEpu0rw4ld4mhwexY",
    authDomain: "bosse-22145.firebaseapp.com",
    projectId: "bosse-22145",
    storageBucket: "bosse-22145.firebasestorage.app",
    messagingSenderId: "164787042932",
    appId: "1:164787042932:web:be30af7b6576f8f0eeaf21",
    measurementId: "G-R7BZBHWP90"
  };

  // Initialize Firebase
  const app = initializeApp(firebaseConfig);
  const analytics = getAnalytics(app);
</script>
